name: Build Kernel on GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    # REMOVE the tmate step entirely - it's blocking your build
    
    - name: Update environment
      run: sudo apt update -y

    - name: Install Dependencies
      run: sudo apt install -y git build-essential zip unzip curl

    - name: Get script
      run: curl -o build_actions.sh -L https://raw.githubusercontent.com/danish3311/valeryn_xiaomi_sm6115/refs/heads/build-actions/build_actions.sh

    - name: Build kernel
      run: bash build_actions.sh

    - name: List build artifacts
      run: find . -maxdepth 5 \( -iname "*.zip" -o -iname "*.tar.xz" \)
      if: always()

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: kernel-chime-${{ github.run_id }}
        path: |
          4.19*.zip
          *kernel-prebuilt*.tar.xz
        if-no-files-found: error
